### ISSUE TITLE
player character in index are too large

### ISSUE THREAD

**Issue by jeraiii** [kevinkickback/Tashas-Notes-of-Everything#1] opened 2024-04-28 13:11 UTC
the images of the player characters on the index page are really big and not in the neat cover type like last time or on the readme page

**Comment by kevinkickback** [comment] 2024-04-28 19:06
Interesting. It seems to be displaying correctly on the devices I have tested. Would you mind taking a screenshot so I can see the problem? You can use the old Cards.css in the mean time. Just extract the file below and move it into the ".obsidian/snippets/" folder and overwrite.

[Cards.zip](https://github.com/kevinkickback/Tashas-Notes-of-Everything/files/15143279/Cards.zip)

**Comment by jeraiii** [comment] 2024-04-29 12:37
![image](https://github.com/kevinkickback/Tashas-Notes-of-Everything/assets/44616099/49cd0aef-4545-460e-86ef-179650ef9232)

Here's what I'm seeing on my end. I just grabbed what's up on the repo. Thanks so much!

**Comment by kevinkickback** [comment] 2024-04-29 17:55
That looks like "Cards" isn't enabled under Settings > Appearance > CSS Snippets.

**Comment by jeraiii** [comment] 2024-04-29 18:57
Sadly I do i have it already enabled.
![image](https://github.com/kevinkickback/Tashas-Notes-of-Everything/assets/44616099/69c23b86-9f68-4295-98e1-82a69ef47294)

**Comment by kevinkickback** [comment] 2024-04-29 19:22
Hmmm okay. Let's try a couple troubleshooting options:

1. Toggle on/off the other snippets one by one to see if they have any effect on the player cards.
2. Repeat the same thing again but with the community plugins.
3. Ensure the dataview code block on index includes the following line exactly:
    `dv.container.className += ' hideSort cards cards-cover cards-1-1';`
4. Test the old "Cards.css" posted above to see if it has the same issue
5. Download a previous version of the vault under releases and see if that one is working.

I would test all this myself but unfortunately everything is displaying correctly on my end.

**Comment by kevinkickback** [comment] 2024-05-05 02:07
I was able to reproduce the bug. This should now be fixed in the latest version.

**Comment by kevinkickback** [comment] 2024-05-05 02:09
I was able to reproduce the bug. This should now be fixed in the latest version.

**Closed by kevinkickback** 2024-05-05 02:09 UTC
Labels: bug
